"""Create all tables for agape v3

Revision ID: 7cbd669685c9
Revises: dd4672974a73
Create Date: 2025-11-27 13:00:35.462888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7cbd669685c9'
down_revision: Union[str, None] = 'dd4672974a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organization_name', 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_email_expires', 'otp_codes', ['email', 'expires_at'], unique=False)
    op.create_index('idx_otp_phone_expires', 'otp_codes', ['phone', 'expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('parishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parish_name', 'parishes', ['name'], unique=False)
    op.create_index(op.f('ix_parishes_id'), 'parishes', ['id'], unique=False)
    op.create_index(op.f('ix_parishes_name'), 'parishes', ['name'], unique=False)
    op.create_table('registration_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reg_email_expires', 'registration_sessions', ['email', 'expires_at'], unique=False)
    op.create_index('idx_reg_session_id', 'registration_sessions', ['registration_id'], unique=False)
    op.create_index(op.f('ix_registration_sessions_email'), 'registration_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_registration_sessions_expires_at'), 'registration_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_registration_sessions_id'), 'registration_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_registration_sessions_registration_id'), 'registration_sessions', ['registration_id'], unique=True)
    op.create_table('user_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_org', 'user_organizations', ['user_id', 'organization_id'], unique=True)
    op.create_index(op.f('ix_user_organizations_id'), 'user_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_user_organizations_organization_id'), 'user_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_user_id'), 'user_organizations', ['user_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('donation_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hide_amount', sa.Boolean(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_category', 'channels', ['category'], unique=False)
    op.create_index('idx_channel_id_code', 'channels', ['id_code'], unique=False)
    op.create_index('idx_channel_name', 'channels', ['name'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_id_code'), 'channels', ['id_code'], unique=True)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_follow_follower_followed', 'follows', ['follower_id', 'followed_id'], unique=True)
    op.create_index('idx_follow_status', 'follows', ['status'], unique=False)
    op.create_index(op.f('ix_follows_followed_id'), 'follows', ['followed_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_receiver_created', 'notifications', ['receiver_id', 'created_at'], unique=False)
    op.create_index('idx_notif_type', 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_push_token', 'push_tokens', ['token'], unique=False)
    op.create_index('idx_push_token_user', 'push_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_story_expires', 'stories', ['expires_at'], unique=False)
    op.create_index('idx_story_user_created', 'stories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    op.create_index(op.f('ix_stories_expires_at'), 'stories', ['expires_at'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_setting', 'user_settings', ['user_id', 'key'], unique=True)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_session_id', 'verification_sessions', ['session_id'], unique=False)
    op.create_index('idx_verification_user', 'verification_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_id'), 'verification_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_session_id'), 'verification_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_verification_sessions_user_id'), 'verification_sessions', ['user_id'], unique=False)
    op.create_table('channel_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_channel_admin', 'channel_admins', ['user_id', 'channel_id'], unique=True)
    op.create_index(op.f('ix_channel_admins_channel_id'), 'channel_admins', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_admins_id'), 'channel_admins', ['id'], unique=False)
    op.create_index(op.f('ix_channel_admins_user_id'), 'channel_admins', ['user_id'], unique=False)
    op.create_table('channel_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_alert_created', 'channel_alerts', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_channel_alerts_channel_id'), 'channel_alerts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_alerts_id'), 'channel_alerts', ['id'], unique=False)
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_setting', 'channel_settings', ['channel_id', 'key'], unique=True)
    op.create_index(op.f('ix_channel_settings_channel_id'), 'channel_settings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_settings_id'), 'channel_settings', ['id'], unique=False)
    op.create_table('channel_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_channel_sub', 'channel_subscriptions', ['user_id', 'channel_id'], unique=True)
    op.create_index(op.f('ix_channel_subscriptions_channel_id'), 'channel_subscriptions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_subscriptions_id'), 'channel_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_channel_subscriptions_user_id'), 'channel_subscriptions', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_channel', 'conversations', ['channel_id'], unique=False)
    op.create_index('idx_conversation_type', 'conversations', ['type'], unique=False)
    op.create_index(op.f('ix_conversations_channel_id'), 'conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('event_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('allow_installments', sa.Boolean(), nullable=False),
    sa.Column('reservation_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_deadline', sa.String(length=50), nullable=True),
    sa.Column('goal_attendees', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_channel_date', 'events', ['channel_id', 'start_date'], unique=False)
    op.create_index('idx_event_dates', 'events', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_events_channel_id'), 'events', ['channel_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('hidden_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_hidden_channel', 'hidden_channels', ['user_id', 'channel_id'], unique=True)
    op.create_index(op.f('ix_hidden_channels_channel_id'), 'hidden_channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_hidden_channels_id'), 'hidden_channels', ['id'], unique=False)
    op.create_index(op.f('ix_hidden_channels_user_id'), 'hidden_channels', ['user_id'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_poll_channel_created', 'polls', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_polls_channel_id'), 'polls', ['channel_id'], unique=False)
    op.create_index(op.f('ix_polls_creator_id'), 'polls', ['creator_id'], unique=False)
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_code', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('posttag', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_suspected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_author', 'posts', ['author_id'], unique=False)
    op.create_index('idx_post_channel_created', 'posts', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_post_id_code', 'posts', ['id_code'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_id_code'), 'posts', ['id_code'], unique=True)
    op.create_index(op.f('ix_posts_posttag'), 'posts', ['posttag'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_code', sa.String(length=50), nullable=False),
    sa.Column('text_comment', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_author', 'comments', ['author_id'], unique=False)
    op.create_index('idx_comment_parent', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_comment_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_id_code'), 'comments', ['id_code'], unique=True)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participant_conv_user', 'conversation_participants', ['conversation_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_id'), 'conversation_participants', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('discount_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_discount_event_code', 'discount_codes', ['event_id', 'code'], unique=True)
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=False)
    op.create_index(op.f('ix_discount_codes_event_id'), 'discount_codes', ['event_id'], unique=False)
    op.create_index(op.f('ix_discount_codes_id'), 'discount_codes', ['id'], unique=False)
    op.create_table('event_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_alert_created', 'event_alerts', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_alerts_event_id'), 'event_alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_alerts_id'), 'event_alerts', ['id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=100), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('ticket_used', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_pending', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_option', sa.String(length=50), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('installment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('total_attendees', sa.Integer(), nullable=False),
    sa.Column('include_user', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_reg_ticket', 'event_registrations', ['ticket_code'], unique=False)
    op.create_index('idx_event_reg_user', 'event_registrations', ['user_id', 'event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_id'), 'event_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_event_registrations_registration_date'), 'event_registrations', ['registration_date'], unique=False)
    op.create_index(op.f('ix_event_registrations_ticket_code'), 'event_registrations', ['ticket_code'], unique=True)
    op.create_index(op.f('ix_event_registrations_user_id'), 'event_registrations', ['user_id'], unique=False)
    op.create_table('hidden_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_hidden_post', 'hidden_posts', ['user_id', 'post_id'], unique=True)
    op.create_index(op.f('ix_hidden_posts_id'), 'hidden_posts', ['id'], unique=False)
    op.create_index(op.f('ix_hidden_posts_post_id'), 'hidden_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_hidden_posts_user_id'), 'hidden_posts', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('send_as_channel', sa.Boolean(), nullable=False),
    sa.Column('is_system_message', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_message_sender', 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_poll_option_poll', 'poll_options', ['poll_id', 'order'], unique=False)
    op.create_index(op.f('ix_poll_options_id'), 'poll_options', ['id'], unique=False)
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_table('post_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_post_fav', 'post_favorites', ['user_id', 'post_id'], unique=True)
    op.create_index(op.f('ix_post_favorites_id'), 'post_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_post_favorites_post_id'), 'post_favorites', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_favorites_user_id'), 'post_favorites', ['user_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_post_like', 'post_likes', ['user_id', 'post_id'], unique=True)
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_table('post_prays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_post_pray', 'post_prays', ['user_id', 'post_id'], unique=True)
    op.create_index(op.f('ix_post_prays_id'), 'post_prays', ['id'], unique=False)
    op.create_index(op.f('ix_post_prays_post_id'), 'post_prays', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_prays_user_id'), 'post_prays', ['user_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_comment_like', 'comment_likes', ['user_id', 'comment_id'], unique=True)
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_id'), 'comment_likes', ['id'], unique=False)
    op.create_index(op.f('ix_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    op.create_table('event_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=255), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_registration', 'event_transactions', ['registration_id'], unique=False)
    op.create_index('idx_transaction_stripe', 'event_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_event_transactions_id'), 'event_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_event_transactions_registration_id'), 'event_transactions', ['registration_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reaction_msg_user', 'message_reactions', ['message_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_id'), 'message_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.create_table('message_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_message', 'message_reports', ['message_id'], unique=False)
    op.create_index('idx_report_status', 'message_reports', ['status'], unique=False)
    op.create_index(op.f('ix_message_reports_id'), 'message_reports', ['id'], unique=False)
    op.create_index(op.f('ix_message_reports_message_id'), 'message_reports', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reports_reporter_id'), 'message_reports', ['reporter_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_poll_vote_user_poll', 'poll_votes', ['user_id', 'poll_id'], unique=True)
    op.create_index(op.f('ix_poll_votes_id'), 'poll_votes', ['id'], unique=False)
    op.create_index(op.f('ix_poll_votes_option_id'), 'poll_votes', ['option_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_user_id'), 'poll_votes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('nombre', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('apellidos', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('genero', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('primary_organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('parish_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'parishes', ['parish_id'], ['id'])
    op.create_foreign_key(None, 'users', 'organizations', ['primary_organization_id'], ['id'])
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'parish_id')
    op.drop_column('users', 'primary_organization_id')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'telefono')
    op.drop_column('users', 'genero')
    op.drop_column('users', 'fecha_nacimiento')
    op.drop_column('users', 'apellidos')
    op.drop_column('users', 'nombre')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_poll_votes_user_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_option_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_id'), table_name='poll_votes')
    op.drop_index('idx_poll_vote_user_poll', table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_message_reports_reporter_id'), table_name='message_reports')
    op.drop_index(op.f('ix_message_reports_message_id'), table_name='message_reports')
    op.drop_index(op.f('ix_message_reports_id'), table_name='message_reports')
    op.drop_index('idx_report_status', table_name='message_reports')
    op.drop_index('idx_report_message', table_name='message_reports')
    op.drop_table('message_reports')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_id'), table_name='message_reactions')
    op.drop_index('idx_reaction_msg_user', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_event_transactions_registration_id'), table_name='event_transactions')
    op.drop_index(op.f('ix_event_transactions_id'), table_name='event_transactions')
    op.drop_index('idx_transaction_stripe', table_name='event_transactions')
    op.drop_index('idx_transaction_registration', table_name='event_transactions')
    op.drop_table('event_transactions')
    op.drop_index(op.f('ix_comment_likes_user_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_index('idx_user_comment_like', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index(op.f('ix_post_prays_user_id'), table_name='post_prays')
    op.drop_index(op.f('ix_post_prays_post_id'), table_name='post_prays')
    op.drop_index(op.f('ix_post_prays_id'), table_name='post_prays')
    op.drop_index('idx_user_post_pray', table_name='post_prays')
    op.drop_table('post_prays')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.drop_index('idx_user_post_like', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_post_favorites_user_id'), table_name='post_favorites')
    op.drop_index(op.f('ix_post_favorites_post_id'), table_name='post_favorites')
    op.drop_index(op.f('ix_post_favorites_id'), table_name='post_favorites')
    op.drop_index('idx_user_post_fav', table_name='post_favorites')
    op.drop_table('post_favorites')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_index(op.f('ix_poll_options_id'), table_name='poll_options')
    op.drop_index('idx_poll_option_poll', table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_sender', table_name='messages')
    op.drop_index('idx_message_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hidden_posts_user_id'), table_name='hidden_posts')
    op.drop_index(op.f('ix_hidden_posts_post_id'), table_name='hidden_posts')
    op.drop_index(op.f('ix_hidden_posts_id'), table_name='hidden_posts')
    op.drop_index('idx_user_hidden_post', table_name='hidden_posts')
    op.drop_table('hidden_posts')
    op.drop_index(op.f('ix_event_registrations_user_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_ticket_code'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_registration_date'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_index('idx_event_reg_user', table_name='event_registrations')
    op.drop_index('idx_event_reg_ticket', table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_event_alerts_id'), table_name='event_alerts')
    op.drop_index(op.f('ix_event_alerts_event_id'), table_name='event_alerts')
    op.drop_index('idx_event_alert_created', table_name='event_alerts')
    op.drop_table('event_alerts')
    op.drop_index(op.f('ix_discount_codes_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_event_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_index('idx_discount_event_code', table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_index('idx_participant_conv_user', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id_code'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index('idx_comment_post_created', table_name='comments')
    op.drop_index('idx_comment_parent', table_name='comments')
    op.drop_index('idx_comment_author', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_posttag'), table_name='posts')
    op.drop_index(op.f('ix_posts_id_code'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('idx_post_id_code', table_name='posts')
    op.drop_index('idx_post_channel_created', table_name='posts')
    op.drop_index('idx_post_author', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_creator_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_channel_id'), table_name='polls')
    op.drop_index('idx_poll_channel_created', table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_hidden_channels_user_id'), table_name='hidden_channels')
    op.drop_index(op.f('ix_hidden_channels_id'), table_name='hidden_channels')
    op.drop_index(op.f('ix_hidden_channels_channel_id'), table_name='hidden_channels')
    op.drop_index('idx_user_hidden_channel', table_name='hidden_channels')
    op.drop_table('hidden_channels')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_channel_id'), table_name='events')
    op.drop_index('idx_event_dates', table_name='events')
    op.drop_index('idx_event_channel_date', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel_id'), table_name='conversations')
    op.drop_index('idx_conversation_type', table_name='conversations')
    op.drop_index('idx_conversation_channel', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_channel_subscriptions_user_id'), table_name='channel_subscriptions')
    op.drop_index(op.f('ix_channel_subscriptions_id'), table_name='channel_subscriptions')
    op.drop_index(op.f('ix_channel_subscriptions_channel_id'), table_name='channel_subscriptions')
    op.drop_index('idx_user_channel_sub', table_name='channel_subscriptions')
    op.drop_table('channel_subscriptions')
    op.drop_index(op.f('ix_channel_settings_id'), table_name='channel_settings')
    op.drop_index(op.f('ix_channel_settings_channel_id'), table_name='channel_settings')
    op.drop_index('idx_channel_setting', table_name='channel_settings')
    op.drop_table('channel_settings')
    op.drop_index(op.f('ix_channel_alerts_id'), table_name='channel_alerts')
    op.drop_index(op.f('ix_channel_alerts_channel_id'), table_name='channel_alerts')
    op.drop_index('idx_channel_alert_created', table_name='channel_alerts')
    op.drop_table('channel_alerts')
    op.drop_index(op.f('ix_channel_admins_user_id'), table_name='channel_admins')
    op.drop_index(op.f('ix_channel_admins_id'), table_name='channel_admins')
    op.drop_index(op.f('ix_channel_admins_channel_id'), table_name='channel_admins')
    op.drop_index('idx_user_channel_admin', table_name='channel_admins')
    op.drop_table('channel_admins')
    op.drop_index(op.f('ix_verification_sessions_user_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_session_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_id'), table_name='verification_sessions')
    op.drop_index('idx_verification_user', table_name='verification_sessions')
    op.drop_index('idx_verification_session_id', table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index('idx_user_setting', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_expires_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.drop_index('idx_story_user_created', table_name='stories')
    op.drop_index('idx_story_expires', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_user_expires', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.drop_index('idx_push_token_user', table_name='push_tokens')
    op.drop_index('idx_push_token', table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notif_type', table_name='notifications')
    op.drop_index('idx_notif_receiver_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_id'), table_name='follows')
    op.drop_index('idx_follow_status', table_name='follows')
    op.drop_index('idx_follow_follower_followed', table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_id_code'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index('idx_channel_name', table_name='channels')
    op.drop_index('idx_channel_id_code', table_name='channels')
    op.drop_index('idx_channel_category', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_user_organizations_user_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_organization_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_id'), table_name='user_organizations')
    op.drop_index('idx_user_org', table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_index(op.f('ix_registration_sessions_registration_id'), table_name='registration_sessions')
    op.drop_index(op.f('ix_registration_sessions_id'), table_name='registration_sessions')
    op.drop_index(op.f('ix_registration_sessions_expires_at'), table_name='registration_sessions')
    op.drop_index(op.f('ix_registration_sessions_email'), table_name='registration_sessions')
    op.drop_index('idx_reg_session_id', table_name='registration_sessions')
    op.drop_index('idx_reg_email_expires', table_name='registration_sessions')
    op.drop_table('registration_sessions')
    op.drop_index(op.f('ix_parishes_name'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_id'), table_name='parishes')
    op.drop_index('idx_parish_name', table_name='parishes')
    op.drop_table('parishes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_index('idx_otp_phone_expires', table_name='otp_codes')
    op.drop_index('idx_otp_email_expires', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index('idx_organization_name', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
